INSERT INTO image (id, bytes) VALUES (nextval('image_seq'), 'LogoM.png');


insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'Sinfonia delle Stelle', 'Festival', '10-08-2024' ,'concerto sotto il cielo stellato', 1, 70);
insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'Avventura nelle nuvole','Sfide verticali', '18-06-2023','esperienza estrema di paracadutismo', null, 90);
insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'Conferenza delle menti brillanti','Fiera', '24-02-2016','condivisione di conoscenze e idee innovative', null, 60);
insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'Serata enigmatica','Cena con spettacolo', '07-12-1022','un viaggio nel mistero', null, 50);
insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'Mostra dei sapori del Mondo','Evento culinario', '27-04-2013', 'celebrazione delle diversità gastronomiche globali', null, 80);
insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'Onda su Onda','Contest', '11-07-2023','festa della musica e del benessere', null, 70);
insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'Notte dei Racconti Incantati','Evento sociale', '15-08-2024', 'serata di narrazioni e fantasia', null, 40);
insert into evento (id, nome, tipologia, data, descrizione, image_id, prezzo) values(nextval('evento_seq'), 'San Valentino','Serata Romantica', '14-03-2024', 'Celebra l''amore in una serata magica sotto le stelle nella splendida cornice del ristorante La Vela.', null, 40);


INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'un''esperienza emozionante e adrenalinica. L''evento di paracadutismo ha offerto ai partecipanti la possibilità di vivere la straordinaria sensazione di cadere liberamente attraverso il cielo. L''organizzazione è stata impeccabile, garantendo sicurezza e professionalità in ogni fase. I panorami mozzafiato e l''adrenalina pura hanno reso questa avventura indimenticabile per tutti gli appassionati di emozioni forti e di nuove sfide.', 5, 'Mario Rossi', 51, null);
INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'è stata un''esperienza musicale straordinaria. L''orchestra ha eseguito con maestria pezzi classici ispirati all''universo, creando un''atmosfera magica e coinvolgente. Le proiezioni stellari che accompagnavano la musica hanno aggiunto un tocco visivo affascinante, trasportando il pubblico in un viaggio attraverso il cosmo. Una serata indimenticabile per gli amanti della musica e delle stelle.', 4, 'Mario Rossi', 1, null);
INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'non sono pienamente soddisfatto delle aspettative. Sebbene l''orchestra abbia eseguito i pezzi con competenza, l''evento nel complesso è risultato meno coinvolgente di quanto sperato.', 2, 'Mario Rossi', 1, null);
INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'La serata di narrazioni e fantasia è stata un''occasione incantevole per immergersi in storie avvincenti e creatività senza limiti. Gli storyteller hanno saputo coinvolgere il pubblico con racconti ben strutturati e suggestivi, trasportandoci in mondi fantastici e emozionanti. Tuttavia, alcune narrazioni hanno mancato di originalità o profondità, rendendo l''esperienza altalenante. L''atmosfera generale era accogliente e intima, ideale per chi ama lasciarsi trasportare dalla magia delle parole. In definitiva, una serata piacevole ma con margini di miglioramento nelle performance narrative.', 3, 'Mario Rossi', 301, null);
INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'un''esperienza culinaria eccezionale. L''evento ha offerto un viaggio attraverso sapori e tradizioni di tutto il mondo, con stand che rappresentavano una vasta gamma di cucine internazionali. Gli chef hanno presentato piatti autentici e deliziosi, accompagnati da spiegazioni sulle loro origini culturali. L''atmosfera era vivace e accogliente, permettendo ai partecipanti di esplorare nuove culture attraverso il cibo. Un appuntamento imperdibile per gli amanti della gastronomia e della scoperta.', 4, 'Mario Rossi', 201, null);
INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'è stata un''esperienza rigenerante e piacevole. L''evento ha combinato armoniosamente concerti dal vivo e attività di benessere. Gli artisti hanno creato un''atmosfera rilassante con la loro musica, mentre le sessioni di benessere hanno offerto momenti di tranquillità e rinvigorimento. Un evento perfetto per chi cerca un equilibrio tra intrattenimento e relax.', 5, 'Mario Rossi', 251, null);
INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'Nonostante la cornice suggestiva, l''evento è stato compromesso da diversi problemi organizzativi. Il servizio è stato lento e disorganizzato, con tempi di attesa eccessivi per i piatti. Inoltre, l''atmosfera romantica è stata disturbata da rumori provenienti da altre tavolate e da un''eccessiva confusione nell''organizzazione degli spazi. Il cibo, pur decente, non ha raggiunto le aspettative per un ristorante di questa categoria. ', 1, 'Mario Rossi', 351, null);
INSERT INTO Recensione (id, commento, voto, cliente, evento_id, image_id) VALUES (nextval('recensione_seq'), 'Nel complesso, un''idea promettente ma con esecuzione inconsistente. Sebbene l''idea di combinare musica dal vivo con attività di benessere fosse interessante, l''organizzazione ha mostrato alcune lacune.', 2, 'Mario Rossi', 251, null);


